In [31]:
import pandas as pd
import sklearn
import numpy as np

%matplotlib inline

main_df = pd.read_csv("CencusIncome.data.txt", header = None)
main_df = main_df.rename(columns={0: 'age', 1: 'workclass', 2: 'fnlwgt', 3: 'education', 4: 'education-num', 5: 'marital-status', 6: 'occupation',7: 'relationship', 8: 'race',9: 'sex', 10: 'capital-gain', 11: 'capital-loss', 12: 'hours-per-week', 13: 'native-country', 14: 'label'})

y = np.array(main_df['label'])
x = np.array(main_df.drop(['label'],1))

main_df.head(1000)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,34,Private,202046,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,35,United-States,>50K
971,28,Private,161538,Bachelors,13,Never-married,Tech-support,Not-in-family,White,Female,0,0,35,United-States,<=50K
972,67,Private,105252,Bachelors,13,Widowed,Exec-managerial,Not-in-family,White,Male,0,2392,40,United-States,>50K
973,37,Private,200153,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
974,44,Private,32185,HS-grad,9,Never-married,Transport-moving,Unmarried,White,Male,0,0,70,United-States,<=50K
975,25,Private,178326,Some-college,10,Never-married,Sales,Not-in-family,White,Female,0,0,40,United-States,<=50K
976,21,Private,255957,Some-college,10,Never-married,Exec-managerial,Not-in-family,White,Female,4101,0,40,United-States,<=50K
977,40,State-gov,188693,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,35,United-States,>50K
978,78,Private,182977,HS-grad,9,Widowed,Other-service,Not-in-family,Black,Female,2964,0,40,United-States,<=50K
979,34,Private,159929,HS-grad,9,Divorced,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
980,49,Private,123207,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,44,United-States,<=50K
981,22,Private,284317,Assoc-acdm,12,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
982,23,?,184699,HS-grad,9,Never-married,?,Unmarried,Black,Female,0,0,40,United-States,<=50K
983,60,Self-emp-not-inc,154474,HS-grad,9,Never-married,Farming-fishing,Unmarried,White,Male,0,0,42,United-States,<=50K
984,45,Local-gov,318280,HS-grad,9,Widowed,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,>50K
985,63,Private,254907,Assoc-voc,11,Divorced,Other-service,Not-in-family,White,Female,0,0,20,United-States,<=50K
986,41,Private,349221,HS-grad,9,Never-married,Craft-repair,Own-child,Black,Female,0,0,35,United-States,<=50K
987,47,Private,335973,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
988,44,Private,126701,HS-grad,9,Divorced,Craft-repair,Unmarried,White,Male,0,0,40,United-States,<=50K
989,51,Private,122159,Some-college,10,Widowed,Prof-specialty,Not-in-family,White,Female,3325,0,40,United-States,<=50K
990,46,Private,187370,Bachelors,13,Never-married,Sales,Not-in-family,White,Male,0,1504,40,United-States,<=50K
991,41,Private,194636,Assoc-voc,11,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,<=50K
992,50,Self-emp-not-inc,124793,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,United-States,<=50K
993,47,Private,192835,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,50,United-States,>50K
994,35,Private,290226,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,45,United-States,<=50K
995,56,Private,112840,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,55,United-States,>50K
996,45,Private,89325,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Male,0,0,45,United-States,<=50K
997,48,Federal-gov,33109,Bachelors,13,Divorced,Exec-managerial,Unmarried,White,Male,0,0,58,United-States,>50K
998,40,Private,82465,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,2580,0,40,United-States,<=50K
999,39,Self-emp-inc,329980,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,15024,0,50,United-States,>50K

In [30]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
gnb = GaussianNB()

for column in main_df.columns.values:
    le.fit(main_df[column])
    main_df[column] = le.transform(main_df[column])

main_df.head(1000)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,label
0,22,7,2671,9,12,4,1,1,4,1,25,0,39,39,0
1,33,6,2926,9,12,2,4,0,4,1,0,0,12,39,0
2,21,4,14086,11,8,0,6,1,4,1,0,0,39,39,0
3,36,4,15336,1,6,2,6,0,2,1,0,0,39,39,0
4,11,4,19355,9,12,2,10,5,2,0,0,0,39,5,0
5,20,4,17700,12,13,2,4,5,4,0,0,0,39,39,0
6,32,4,8536,6,4,3,8,1,2,0,0,0,15,23,0
7,35,6,13620,11,8,2,4,0,4,1,0,0,44,39,1
8,14,4,1318,12,13,4,10,1,4,0,105,0,49,39,1
9,25,4,8460,9,12,2,4,0,4,1,79,0,39,39,1
10,20,4,17530,15,9,2,4,0,2,1,0,0,76,39,1
11,13,7,7077,9,12,2,10,0,1,1,0,0,39,19,1
12,6,4,5772,9,12,4,1,3,4,0,0,0,29,39,0
13,15,4,13217,7,11,4,12,1,2,1,0,0,49,39,0
14,23,4,5722,8,10,2,3,0,1,1,0,0,39,0,1
15,17,4,15963,5,3,2,14,0,0,1,0,0,44,26,0
16,8,6,10163,11,8,4,5,3,4,1,0,0,34,39,0
17,15,4,11257,11,8,4,7,4,4,1,0,0,39,39,0
18,21,4,314,1,6,2,12,0,4,1,0,0,49,39,0
19,26,6,17974,12,13,0,4,4,4,0,0,0,44,39,1
20,23,4,12044,10,15,2,10,0,4,1,0,0,59,39,1
21,37,4,18302,11,8,5,8,4,2,0,0,0,19,39,0
22,18,1,2636,6,4,2,5,0,2,1,0,0,39,39,0
23,26,4,5306,1,6,2,14,0,4,1,0,54,39,39,0
24,42,4,4613,11,8,0,13,4,4,0,0,0,39,39,0
25,39,2,14178,9,12,2,13,0,4,1,0,0,39,39,1
26,2,4,9263,11,8,4,3,3,4,1,0,0,39,39,0
27,37,0,10524,15,9,2,0,0,1,1,0,0,59,35,1
28,22,4,20071,11,8,0,4,1,4,1,0,0,76,39,0
29,32,4,12029,11,8,2,3,0,4,1,0,0,39,39,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,17,4,12944,11,8,2,3,0,4,1,0,0,34,39,1
971,11,4,8645,9,12,4,13,1,4,0,0,0,34,39,0
972,50,4,4295,9,12,6,4,1,4,1,0,75,39,39,1
973,20,4,12747,11,8,2,3,0,4,1,0,0,39,39,0
974,27,4,541,11,8,4,14,4,4,1,0,0,68,39,0
975,8,4,10344,15,9,4,12,1,4,0,0,0,39,39,0
976,4,4,16460,15,9,4,4,1,4,0,67,0,39,39,0
977,23,7,11493,12,13,2,10,0,4,1,0,0,34,39,1
978,61,4,10830,11,8,6,8,1,2,0,47,0,39,39,0
979,17,4,8509,11,8,0,6,3,4,1,0,0,39,39,0
980,32,4,5833,11,8,4,1,1,4,0,0,0,43,39,0
981,5,4,17693,7,11,4,1,1,4,0,0,0,39,39,0
982,6,0,11033,11,8,4,0,4,2,0,0,0,39,39,0
983,43,6,8089,11,8,4,5,4,4,1,0,0,41,39,0
984,28,2,18805,11,8,6,11,1,4,1,0,0,39,39,1
985,46,4,16401,8,10,0,8,1,4,0,0,0,19,39,0
986,24,4,19691,11,8,4,3,3,2,0,0,0,34,39,0
987,30,4,19273,11,8,0,1,4,4,0,0,0,39,39,0
988,27,4,6097,11,8,0,3,4,4,1,0,0,39,39,0
989,34,4,5760,15,9,6,10,1,4,0,53,0,39,39,0
990,29,4,11326,9,12,4,12,1,4,1,0,18,39,39,0
991,24,4,12147,8,10,2,7,0,4,1,0,0,39,39,0
992,33,6,5952,11,8,2,3,0,4,1,0,0,29,39,0
993,30,4,11961,11,8,2,1,0,4,1,0,0,49,39,1
994,18,4,17907,11,8,4,4,1,4,1,0,0,44,39,0
995,39,4,4934,11,8,2,4,0,4,1,0,0,54,39,1
996,28,4,3216,12,13,0,10,1,4,1,0,0,44,39,0
997,31,1,613,9,12,0,4,4,4,1,0,0,57,39,1
998,23,4,2874,15,9,2,7,0,4,1,38,0,39,39,0
999,22,5,19126,9,12,2,4,0,4,1,108,0,49,39,1